Repository ComradeAx0n/you-open-sri-lanka, pull requests merged in 2022-12, with the labels that each got.

#20 Add search engine
  README.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/theme/SearchBar/DocSearch.js
  src/theme/SearchBar/algolia.css
  src/theme/SearchBar/index.js
  src/theme/SearchBar/lunar-search.js
  src/theme/SearchBar/styles.css
  src/theme/SearchBar/templates.js
  src/theme/SearchBar/utils.js
Labels: enhancement

#23 Docs and SEO
  LICENSE_DOCUMENTATION
  docs/about.md
  docs/before-arrive/drone.md
  docs/before-arrive/entry-conditions.md
  docs/before-arrive/things.md
  docs/before-arrive/transfer-animals.md
  docs/before-arrive/visa.md
  docs/business.md
  docs/chats.md
  docs/other.md
  docs/residence/electricity.mdx
  docs/residence/emergency-services.md
  docs/residence/finance.mdx
  docs/residence/gas.md
  docs/residence/holidays.md
  docs/residence/housing.md
  docs/residence/medicine.md
  docs/residence/online-stores.md
  docs/residence/products-goods.md
  docs/residence/services.md
  docs/residence/sim-internet.md
  docs/residence/transport/bus.md
  docs/residence/transport/id.md
  docs/residence/transport/index.md
  docs/residence/transport/rent.md
  docs/residence/transport/train.md
  docs/resources.md
  docs/tourism/attractions.md
  docs/tourism/tours.md
  docusaurus.config.js
  static/img/messages_hstlr.jpeg
  static/robots.txt
Labels: documentation, enhancement, fix

#24 Fix/links to files
  docs/before-arrive/entry-conditions.md
  docs/other.md
  docs/residence/transport/bus.md
  docs/residence/transport/id.md
  docs/residence/transport/rent.md
  docs/residence/transport/train.md
Labels: fix

#25 Doc/common
  docs/before-arrive/entry-conditions.md
  docs/before-arrive/transfer-animals.md
  docs/before-arrive/visa.md
  docs/business.md
  docs/other.md
  docs/residence/finance.mdx
  docs/residence/housing.md
  docs/residence/transport/index.md
  docs/residence/transport/rent.md
  docs/tourism/attractions.md
  static/img/Peoples_WaveApp_leaf_In-01.jpg
  static/img/Peoples_WaveApp_leaf_out-01.jpg
Labels: documentation

#27 change license from CC0 to CC BY-NC-SA
  LICENSE_DOCUMENTATION
  README.md
  docs/about.md
Labels: documentation

#28 Add calendars 2023 year
  docs/residence/holidays.mdx
  static/doc/calendar-holidays.pdf
  static/img/2022_year.png
  static/img/2023_year.png
Labels: documentation
